trigger:
- master  # Replace with your branch name

pool:
  vmImage: 'ubuntu-latest'

variables:
  nodeVersion: '16.x'  # Specify your Node.js version

steps:
# 1. Checkout the repository
- task: Checkout@1
  displayName: 'Checkout Code'

# 2. Install Node.js
- task: UseNode@2
  inputs:
    version: '$(nodeVersion)'
  displayName: 'Set up Node.js'

# 3. Install dependencies
- script: |
    npm install
  displayName: 'Install Dependencies'

# 4. Run the application
- script: |
    node main.js