trigger:
- main  # Replace with your branch name

pool:
  vmImage: 'ubuntu-latest'

variables:
  nodeVersion: '16.x'

steps:
# 1. Install Node.js
- task: UseNode@2
  inputs:
    version: '$(nodeVersion)'
  displayName: 'Set up Node.js'

# 2. Install dependencies
- script: |
    npm install
  displayName: 'Install Dependencies'

# 3. Run the application
- script: |
    node main.js
  displayName: 'Run Node.js Application'
